### PR TITLE
Feat/select default chains bridge

### PR DESCRIPTION
**Pull request by BowLover**
## Description and Motivation

Choose by default the most logic chain depending on current chain in TFM bridge.

I removed last pull request since was kinda hardcoded, now I take info from validChains constant so is scalable as soon as you add future chains there (that I think is the case).

Basically added 2 options:

- If current chain is migaloo Bridge from Migaloo to empty.

- If current chains isn't migaloo bridge from current chain to migaloo.

## Related Issues

Issue #274

---

## Checklist:

- [x] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/CONTRIBUTING.md).
- [x] My pull request has a sound title and description (not something vague like `Update index.md`)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation.
- [x] The code is formatted properly `yarn lint`.
- [x] The project builds and is able to deploy on Netlify `yarn build`.

### CODE REVIEW

**Review by 0xFable — COMMENTED** [review]
Reviewed this, looking good @BowLover. Pls resolve conflicts so it can merge without issue. 🚀

**Comment by BowLover** [comment]
> Reviewed this, looking good @BowLover. Pls resolve conflicts so it can merge without issue. 🚀

Nick added this already, so I close the pr

**Comment by nick134-bit** [comment]
can you reopen your PR ? I actually didnt work on this

**Comment by nick134-bit** [comment]
Already added by @worrex in #319

**Comment by 0xFable** [comment]
Thank you for taking the time on this @BowLover , we will sort you out with something <3

**Pull request closed without merging**
