### PR TITLE
fix: added additional validations to the WhaleInput

### LINKED ISSUE #188: fix/missing input validation
The input fields of this component don't validate any inputs. We should make two changes here:
- Limit the number of characters users can enter to 32 (right now it's unlimited)
- A leading zero must be followed by a point, not a second zero.

Bildschirm­foto 2023-03-04 um 10 44 09

### PR DESCRIPTION
**Pull request by jijicodes**
## Description and Motivation

Added validation to token input fields app-wide to improve ux.

Screenshot 2024-03-01 at 12 07 14 PM

## Related Issues

Resolves #188  

---

## Checklist:

- [x] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/CONTRIBUTING.md).
- [x] My pull request has a sound title and description (not something vague like `Update index.md`)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation.
- [x] The code is formatted properly `yarn lint`.
- [x] The project builds and is able to deploy on Netlify `yarn build`.

### CODE REVIEW

**Comment by nick134-bit** [comment]
Thank you for your PR! can you also add a filter for these cases? :
no negative numbers
not starting with .
@jijicodes

**Comment by jijicodes** [comment]
> Thank you for your PR! can you also add a filter for these cases? : no negative numbers not starting with . @jijicodes

Hey @nick134-bit!
Who could have guessed that those 2 extra validations would be so much trickier than the original two 😇. This issue was a good chance for me to dig into regex and hopefully this time regexes will stick in my head.
Please let me know if there's anything else needed to this PR.

**Comment by jijicodes** [comment]
Re-reading through the original issue, I saw [this](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/issues/188#issuecomment-1454683277) message from @Sen-Com asking for the validation to be applied to the slippage tolerance input so I have pushed these changes as well. 
@nick134-bit

**Review by nick134-bit — APPROVED** [review]
LGTM

**Pull request merged**
